//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTMENT()
        {
            this.USER_DEPARTMENT = new HashSet<USER_DEPARTMENT>();
        }
    
        public decimal DEPARTMENTID { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEPARTMENTPARENTID { get; set; }
        public Nullable<decimal> SINDEX { get; set; }
        public string EXTRAID { get; set; }
        public string EXTRAPID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_DEPARTMENT> USER_DEPARTMENT { get; set; }
    }
}
