//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTIONINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCTIONINFO()
        {
            this.ROLEINFO = new HashSet<ROLEINFO>();
        }
    
        public decimal FUNCTIONID { get; set; }
        public string FUNCTIONNAME { get; set; }
        public string DISPLAYNAME { get; set; }
        public Nullable<decimal> FUNCTIONTYPEID { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXECUTE { get; set; }
        public string CLSNAME { get; set; }
        public Nullable<decimal> SINDEX { get; set; }
    
        public virtual FUNCTIONTYPE FUNCTIONTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLEINFO> ROLEINFO { get; set; }
    }
}
