//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLEINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLEINFO()
        {
            this.FUNCTIONINFO = new HashSet<FUNCTIONINFO>();
            this.USERINFO = new HashSet<USERINFO>();
        }
    
        public decimal ROLEID { get; set; }
        public Nullable<decimal> ROLEPARENTID { get; set; }
        public string ROLENAME { get; set; }
        public string DISPLAYNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> SINDEX { get; set; }
        public Nullable<decimal> ROLETYPEID { get; set; }
    
        public virtual ROLETYPE ROLETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCTIONINFO> FUNCTIONINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERINFO> USERINFO { get; set; }
    }
}
