//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOServer.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<FUNCTIONINFO> FUNCTIONINFO { get; set; }
        public virtual DbSet<FUNCTIONTYPE> FUNCTIONTYPE { get; set; }
        public virtual DbSet<LOGIN_LOG> LOGIN_LOG { get; set; }
        public virtual DbSet<ROLEINFO> ROLEINFO { get; set; }
        public virtual DbSet<ROLETYPE> ROLETYPE { get; set; }
        public virtual DbSet<SYSTEMINFO> SYSTEMINFO { get; set; }
        public virtual DbSet<USER_DEPARTMENT> USER_DEPARTMENT { get; set; }
        public virtual DbSet<USERINFO> USERINFO { get; set; }
        public virtual DbSet<USERTYPE> USERTYPE { get; set; }
        public virtual DbSet<USERLEVEL> USERLEVEL { get; set; }
    }
}
