//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMINFO
    {
        public decimal SYSTEMID { get; set; }
        public string CLIENTID { get; set; }
        public string CLIENTNAME { get; set; }
        public string FLOW { get; set; }
        public string CLIENTSECRETS { get; set; }
        public string REDIRECTURIS { get; set; }
        public string ALLOWEDSCOPES { get; set; }
        public string ACCESSTOKENTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CLIENTURI { get; set; }
        public string REQUIRECONSENT { get; set; }
        public string ALLOWREMEMBERCONSENT { get; set; }
        public string ALLOWACCESSTOALLSCOPES { get; set; }
    }
}
